#!/bin/bash
# ---------------------------------------------------------------------
# Tool: Forensic-Toolbox-AZE
# Created by: Elcan Kerimli 
# Purpose: Automated evidence collection environment (Linux)
# ---------------------------------------------------------------------

# Disclaimer 
# This tool is for educational and professional forensic purposes only.
# The author assumes no liability for misuse.

CYAN='\033[0;36m'
GREEN='\033[0;32m'
NC='\033[0m'

clear
echo -e "${CYAN}***************************************************${NC}"
echo -e "${CYAN}* FORENSIC TOOLBOX - AZERBAIJAN            *${NC}"
echo -e "${CYAN}* Lead Investigator: ELCAN KERIMLI        *${NC}"
echo -e "${CYAN}***************************************************${NC}"
echo ""

# Case adını soruş
read -p "Araşdırma adını daxil edin (məs: Case_001): " case_name

# Qovluq strukturunu yarat
mkdir -p "$case_name"/{evidence,logs,reports,screenshots}
echo -e "${GREEN}[+] Qovluq strukturu uğurla yaradıldı.${NC}"

# Sistem və Müstəntiq məlumatlarını qeyd et
{
    echo "===================================================="
    echo "             DIGITAL FORENSIC METADATA              "
    echo "===================================================="
    echo "Investigation Start : $(date)"
    echo "Lead Investigator   : ELCAN KERIMLI"
    echo "System User         : $USER"
    echo "Machine Kernel      : $(uname -a)"
    echo "===================================================="
} > "$case_name/logs/system_info.txt"

# Hüquqi Hesabat Şablonu (Markdown formatında)
cat <<EOF > "$case_name/reports/report_v1.md"
# Rəqəmsal Araşdırma Hesabatı: $case_name
**investigator:** Elcan Kerimli (@elcankarimli)
**Tarix:** $(date)

---

### 1. ARAŞDIRMA HAQQINDA QISA MƏLUMAT
*Burada hadisənin baş vermə şəraiti və hüquqi əsasları qeyd edilməlidir.*

### 2. SÜBUTLARIN SAXLANMA ZƏNCİRİ (Chain of Custody)
- [ ] Sübutlar toplandı: **Elcan Kerimli** tərəfindən.
- [ ] Saxlanma yeri: "$case_name/evidence"
- [ ] Sistem logları: "$case_name/logs/system_info.txt"

### 3. HÜQUQİ NƏTİCƏLƏR
*Azərbaycan Respublikasının müvafiq kiber-hüquq normalarına əsasən qeydlər.*

---
*Generated by Forensic-Toolbox-AZE*
EOF

echo -e "${GREEN}[+] Hesabat şablonu hazırlandı: $case_name/reports/report_v1.md${NC}"
echo -e "${GREEN}🚀 Hazırdır! Araşdırmaya başlaya bilərsən.${NC}"
